
services:
  # frontend:
  #   build:
  #     context: ./frontie
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontie:/app
  #     - /app/node_modules
  #   networks:
  #     - app-net
  #   environment:
  #     - VITE_API_URL=http://localhost:7000
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./frontie/src
  #         target: /app/src
  #       - action: rebuild
  #         path: ./frontie/package.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-net
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mine
      - JWT_SECRET=hello
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mongo-data: